# Required
Disease/Phenotype terms: autism

# Optional
Additional associated terms: brain, nerve, nervous, neuronal, cerebellum, cerebral, hippocampus, hypothalamus, coretex, cortical, neuron, neurological, behavior
Diseases/Phenotypes to exclude:
