# Required
Disease/Phenotype terms: intellectual disability, mental retardation

# Optional
Additional associated terms: brain, nerve, nervous, neuronal, cerebellum, cerebral, hippocampus, hypothalamus,
  cortex, cortical, neuron, neurological, behavior/neurological


Diseases/Phenotypes to exclude: disability
